### ISSUE TITLE
t7:stop not working

### ISSUE THREAD

**Issue by mcobery** [t7mp/t7mp#66] opened 2012-09-14 21:37 UTC
When using the following configuration and running "mvn t7:run", the server starts.  When I use the same configuration and run "mvn t7:stop" , the server does not stop.  I am running these commands from inside launch files in Eclipse.

Thanks for any help or pointers.  I am using version 0.9.10.M8 of the plugin and 7.0.28 of tomcat.

Regards,
Marc

```
                <plugin>
                    <groupId>com.googlecode.t7mp</groupId>
                    <artifactId>maven-t7-plugin</artifactId>
                    <version>${t7.plugin.version}</version>
                    <configuration>
                                               <!-- MJC Using build output file for potential Maven filtering -->
                        <contextFile>${project.build.outputDirectory}/context.xml</contextFile>
                        <contextPath>${site-context-path}</contextPath>
                        <scanners>
                            <scannerConfiguration>
                                <interval>${appserver.scan.interval}</interval>
                                <endings>%</endings>
                            </scannerConfiguration>
                        </scanners>
                        <scanClasses>true</scanClasses>
                        <tomcatHttpPort>${appserver.runport}</tomcatHttpPort>
                        <tomcatShutdownPort>${appserver.stopport}</tomcatShutdownPort>
                        <tomcatVersion>${tomcat.server.version}</tomcatVersion>
                    </configuration>
                </plugin>
```

**Comment by marcobuss** [comment] 2012-09-14 21:45
Hi,

Please test t7:run-forked and t7:stop-forked. That should work as expected.

**Comment by mcobery** [comment] 2012-09-14 22:36
Hi,

That does work, but then there is no way to debug.  I guess I could run
tomcat with a debug port open but that kind of defeats the purpose of
having a debug launch in Eclipse.  Actually can I set t7 to run in jpda
mode?

Regards,
Marc

**Comment by marcobuss** [comment] 2012-09-14 22:51
Hi,

use the setenv.bat/sh to set your jpda settings. Take a look https://github.com/t7mp/examples

**Comment by jbellmann** [comment] 2012-09-16 19:07
Hi Marc,

does the hint from marco works for you or do you need any further help?

If it works for you, fine. Would you please close the issue then?

@marcobuss 
Thank you for your fast response to this issue.

Cheers
Jörg

**Comment by mcobery** [comment] 2012-09-16 22:15
Jörg,

I am interested in using t7:run from eclipse and the m2 plugin.  The
solution provide does not allow me to do that.  Using the t7:run-forked
will force the developers to use a remote application debugger and I am
afraid that my developers may get a little annoyed but that environment.
Am I incorrect to assume that I should be able to start tomcat with t7:run
in eclipse and stop tomcat with t7:stop from the same eclipse instance?
When I debug it does not appear that the shutdown port is open in the
t7:run.
I wrote a small java application to send the shutdown command but the port
is not open.
Am I doing something wrong?

Thanks,
Marc

**Comment by jbellmann** [comment] 2012-09-17 20:01
Hi Marc,

when you run `mvn t7:run` you start a tomcat-instance within the maven-process as you maybe noticed in the logs. So when the maven-process will be stopped, normally with  `Ctrl+C` a shutdownhook stops the tomcat-instance too.
Thatswhy marco mentioned to use `mvn t7:run-forked` so the tomcat-instance will be started in separate process and does not stop when the maven-process ends.
Of course, your developers have to use a remote-debugger then. But I'm an eclipse-user too and I would say it is easy to use, isn't it?
But you can do it in-process too. But it is not easy to describe here. I will provide some screenshots in the wiki, ok?

Cheers
Jörg

**Comment by jbellmann** [comment] 2012-09-17 21:27
Hi Marc,

here it comes. You forced me to publish my first blog post  ;-)

I hope you find all information you need [here](http://jbellmann.wordpress.com/2012/09/17/how-to-debug-an-java-webapplication-running-with-maven-t7-plugin-in-eclipse/).

Cheers
Jörg

**Comment by mcobery** [comment] 2012-09-17 23:36
Hi Jörg,

Thanks for your quick turn around.  I like your plugin.
Sorry for making you ;)

Do you want me to close the issue?  If som what status should it be?

Regards,
Marc

**Comment by mcobery** [comment] 2012-09-17 23:37
I met to type sorry for making you blog;)

**Comment by jbellmann** [comment] 2012-09-18 08:09
Hi Marc,

yes please, if the issue is solved and it works for you and your colleagues, please close this issue.

Maybe you can have a look at and you can give some hints because in your configuration above you use the contextFile-element? That would be nice.

Cheers
Jörg

**Closed as completed** 2012-09-25 23:42 UTC
